# Generated by Django 2.2.7 on 2019-12-05 19:57

import apps.archivo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proquest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing', models.CharField(max_length=10)),
                ('embargo', models.CharField(max_length=10)),
                ('third_party', models.CharField(max_length=10)),
                ('author_type', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('middle', models.CharField(max_length=50, null=True)),
                ('page_count', models.CharField(max_length=50)),
                ('page_type', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=200)),
                ('apply_copyright', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('comp_date', models.CharField(max_length=20)),
                ('accept_date', models.CharField(max_length=20)),
                ('languaje', models.CharField(max_length=10)),
                ('degree', models.CharField(max_length=50)),
                ('inst_code', models.CharField(max_length=10)),
                ('inst_name', models.CharField(max_length=250)),
                ('processing_code', models.CharField(max_length=50)),
                ('para', models.TextField(blank=True, null=True)),
                ('binary_type', models.CharField(max_length=10)),
                ('binary', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to=apps.archivo.models.content_file_name),
        ),
    ]
